### PR TITLE
Minor helpfull S3 improvements

### PR DESCRIPTION
**Pull request by horror-x**
* Provide last_modified value in get_object results to simplify if_modified_since usage.
* Provide next_marker attribute list_objects to allow to use chunked listing
* Get rid of compile-time/dialyzer warning about deprecated hash functions usage

### CODE REVIEW

**Comment by kkuzmin** [comment]
+1

**Comment by motobob** [comment]
fixes https://github.com/erlcloud/erlcloud/issues/187

**Comment by motobob** [comment]
👍  @smilerlee any comments?

**Comment by smilerlee** [comment]
👍  Great improvements! @motobob are we ready to merge?

**Comment by motobob** [comment]
yes. I was just waiting for your comments

**Comment by motobob** [comment]
@horror-x thank you for contribution.

**Comment by smilerlee** [comment]
@motobob oops, sorry for my late reply, my GitHub notifier extension is out of service somehow.

**Pull request merged**
