### PR TITLE
Fix SNS message attribute Name field

### PR DESCRIPTION
**Pull request by neoascetic**
As per https://docs.aws.amazon.com/sns/latest/api/API_Publish.html

### CODE REVIEW

**Comment by motobob** [comment]
>MessageAttributes.entry.N.Name (key)
MessageAttributes.entry.N.Value (value)

**Review by motobob — APPROVED** [review]
(faceplam) but let's test in real app before merging

**Comment by neoascetic** [comment]
That's why I've created this PR: it didn't work for me otherwise :)
Well, I was using localstack, but anyway.

**Review by nalundgaard — APPROVED** [review]
I'll ship this today along with the License fix for https://github.com/erlcloud/erlcloud/issues/715

**Pull request merged**
