### PR TITLE
Add ability for Erlang applications to log events to AWS CloudWatch Logs

### PR DESCRIPTION
**Pull request by fogfish**
See #510

Content of PR
- [x] [DescribeLogStreams](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DescribeLogStreams.html)
- [x] [PutLogEvents](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html)

Note this PR is still **Work In Progress**, the purpose of such early PR is preview on the work.
 
One of proposal here is improvement of `erlcloud_cloudwatch_logs` code readability  due to excessive amount of nested `case ... of ... end`. I've been struggling with this in other Erlang projects as well, too much of boilerplate code. This problem can be solved by usage of [category pattern](https://github.com/fogfish/datum/blob/master/doc/category.md) and **either** category in particular. 

As an example

```erlang
case a() of
   {ok, A} ->
       case b(A) of
          {ok, B} ->
             c(B);
          {error, _} = Error ->
             Error
      end;
   {error, _} = Error ->
      Error
end
```

11 lines of nested cases are reduced to 1 line of pure functional composition throughout **either** category. 

```erlang
-compile({parse_transform, category}).

[either || a(), b(_), c(_)].
```

Please see more details from documentation of [category pattern](https://github.com/fogfish/datum/blob/master/doc/category.md).

Please compare the implementation of `cw_request`.  It became a sequence of pure functions. 
Let me know, your thought on this pattern.

### CODE REVIEW

**Comment by fogfish** [comment]
@motobob what do you think about this PR. I'll put an effort to fix remaining items if this is OK for you to continue with this proposal otherwise I'll drop deps to my library and problem disappears?

**Comment by fogfish** [comment]
Right, now it is green. Sorry for the hassle but I've stop using R17 long time ago and drop support for this version from all my work. It took me awhile to understand the error about parse transform:
http://erlang.org/pipermail/erlang-bugs/2015-February/004782.html

Now, this PR is ready for your judgement.

**Comment by nalundgaard** [comment]
I'm pretty on the fence about the introduction of the parse transform. It's compact, to be sure, but I'm not sure it's worth the abstraction in terms of strangeness. I'm OK with it if @motobob is, but I'd just as soon see lightly nested cases myself. I lean a bit more towards direct and verbose vs. concise and abstract, but I know that's just me.

**Comment by fogfish** [comment]
Sorry guys, I am resistant to nested case structure. Despite, its simplicity they significantly impact on code readability. My purpose of `datum` library is to eliminate unnecessary boilerplate. IMO, `case` is a boiler place. Nevertheless, this is a your call to control dependencies to external library.

I've removed the deps to `datum`. If this looks ok for you I'll appreciate if you merge PR and update hex package. I am currently developing Erlang library where this feature is absolutely needed.

**Comment by motobob** [comment]
as a side note: be careful with CW logs and Erlang (especially logging stacktraces and huge maps). 
CW is 0.05$/GB and that number adds up very fast if lots of logs are written, enough to kill your bill.  Add as much monitoring as you can for CW side of the things. ;)

**Pull request merged**
