### PR TITLE
Bucket tagging API added and HTTP/HTTPS Proxy configuration support #606

### PR DESCRIPTION
**Pull request by saherkar**
This PR contains following changes:
- Bucket tagging and Object tagging APIs.
- Tagging support in PUT and GET requests.
- Support for HTTP/HTTPS proxy configuration.

#606

### CODE REVIEW

**Comment by motobob** [comment]
LGTM.
@kkuzmin any feedback ? 
 what is the simplest way to verify http proxy stuff?

**Comment by kkuzmin** [comment]
LGTM, too

 > what is the simplest way to verify http proxy stuff?
I think in this case it would be enough to have some minor unit test which mocks lhttp/hackney request function and verifies proxy parameters being passed correctly. But I'm not sure if it worth it.

**Comment by saherkar** [comment]
> what is the simplest way to verify http proxy stuff?

I have tested it with **squid** proxy.
Following are snippet from my testing.

```12> Config=
12> #aws_config{ s3_host = "10.***.***.244",
12> s3_port = 443,
12> access_key_id = "s************************==",
12> secret_access_key = "z**********************==",
12> s3_scheme = "https://",
12> s3_bucket_access_method = path,
12> http_client_options = #http_client_options{proxy = {"10.***.***.209", 3128}, proxy_auth = {<<"v****g">>, <<"v*****g">>}}
12> }.
#aws_config{as_host = "autoscaling.amazonaws.com",
            ec2_host = "ec2.amazonaws.com",
            iam_host = "iam.amazonaws.com",
            sts_host = "sts.amazonaws.com",s3_scheme = "https://",
            s3_host = "10.***.***.244",s3_port = 443,
            s3_follow_redirect = false,s3_follow_redirect_count = 2,
            s3_bucket_access_method = path,s3_bucket_after_host = false,
            sdb_host = "sdb.amazonaws.com",
            elb_host = "elasticloadbalancing.amazonaws.com",
            rds_host = "rds.us-east-1.amazonaws.com",
            ses_host = "email.us-east-1.amazonaws.com",
            sqs_host = "queue.amazonaws.com",sqs_protocol = undefined,
            sqs_port = undefined,emr_scheme = "https://",
            emr_host = "elasticmapreduce.us-east-1.amazonaws.com",
            emr_port = undefined,sns_scheme = "http://",
            sns_host = "sns.amazonaws.com",
            mturk_host = "mechanicalturk.amazonaws.com",
            mon_host = "monitoring.amazonaws.com",mon_port = undefined,
            mon_protocol = undefined,
            ddb_scheme = [...],...}
13> erlcloud_s3:list_buckets(Config).
[{owner,[{id,"admin"},{display_name,"admin"}]},
 {buckets,[[{name,"bk"},
            {creation_date,{{2018,9,18},{7,35,13}}}]]}]
```
As suggested, proxy configuration validation can be possible in unit test.

**Comment by motobob** [comment]
thanks for adding the test

**Pull request merged**
