### PR TITLE
Fix GHA

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Opening this as Draft to check everything is as expected.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
I don't think the "execute rebar2 part is working as expected". Let me look at it closer.

**Comment by paulo-ferraz-oliveira** [comment]
This seems to iron it out:
1. we build (CI) over multiple Erlang versions (a bug in the previous pull request prevented this from happening)
2. we run over `rebar` and `rebar3`

CI is only blocked because of Travis CI. Speaking of which, I'm going to remove it, [as @motobob implied should be done](https://github.com/erlcloud/erlcloud/issues/675#issuecomment-741712340).

**Review by nalundgaard — APPROVED** [review]
Man, this is wonderful! Thanks @paulo-ferraz-oliveira!

**Review by nalundgaard — APPROVED** [review]

**Comment by nalundgaard** [comment]
> **Edit**: this means `deploy` from `.travis.yml` is no longer available.

I always do it by hand anyway, we can sort that out later. 🤷

**Comment by paulo-ferraz-oliveira** [comment]
> I always do it by hand anyway, we can sort that out later.

Sure. I was asking around the other day (Erlang Slack) about how to automate this (publishing to Hex.pm), and was told it's not a very good practice to automate it, especially since you might not be pushing what you think you are (on the shell, at least, you have a notion of what it is).

**Pull request merged**
