### PR TITLE
Fixes for Erlang/OTP 19.0

### PR DESCRIPTION
**Pull request by okeuday**
* -spec syntax is fixed to not cause compilation syntax errors
* -include_lib for erlcloud is changed to -include to work with rebar2

Other changes that would be nice, but are not included in this pull request are mentioned in the issue  #278

### CODE REVIEW

**Comment by motobob** [comment]
this is great to hear a PR for prelim support for R19 after that few days of announce!
Before we start this venture amy I ask to include R19 into travis targets(within this PR) as current auto checks are irrelevant to the scope changes here.

**Comment by okeuday** [comment]
@motobob 19.0 has only had a rc1 release so far, so no official release has happened yet.  This means that it can't be added to travis yet, since travis won't be including it in images yet.

**Comment by motobob** [comment]
I agree that it's a little early...
However, `kerl` has it so that way it be patched. 
I'm just not yet comfortable merging such a big change in specs all over the place. especially given that dialyzer was not that happy even with the original number of specs. 

Can you comment on:
>-include_lib for erlcloud is changed to -include to work with rebar2

majority of consumer of this library uses rebar2 and it works all fine with then.  what specific issue are we fixing here. I'm both hands up for the change  (probably with a separate PR) but I would like here a specific problem we are addressing.

**Comment by okeuday** [comment]
@motobob The include_lib usage with erlcloud will not work if the erlcloud repo is cloned into a directory name that does not match "erlcloud" (at least with rebar2 at tag `2.1.0-pre`, I have used an old tag to avoid instability that was common in the past with the rebar2 development and that tag proved to provide all the critical functionality without new problems, I haven't tried the new tags with this specific compilation issue but would expect the same result).

A separate concern is the unfortunate use of {vsn, git} in the .app.src file, which does not match the http://erlang.org/doc/man/app.html format as defined by Erlang/OTP (an atom rather than a string).  While you might not think this matters, since the typical use of the repo is to depend on rebar to substitute the tag name, that depends on usage within this repo, and ignores using the source code as a directory elsewhere.  It is much more dependable to have a string version that is updated manually, and viewable in the git history, even if commits are deleted or changed within the commit history.

**Comment by smilerlee** [comment]
Using `-include` instead of `-include_lib` seems much more reasonable, as far as I can tell most of the official libraries are using this approach.
It would be great to have a separate PR.

**Comment by okeuday** [comment]
@smilerlee The reason these two changes are together is due to both being required for getting erlcloud back to a state where it compiles with Erlang/OTP 19.0.  You will notice the older source code does use `-include` instead of `-include_lib`.  This is just fixing a regression with the newer source code.  The `-spec` changes are changing the syntax to the accepted format.  I find it strange that we are still talking about the changes, due to none of the changes affecting the functionality or the compilation result.

**Comment by smilerlee** [comment]
@okeuday I vote for both two changes.

* `-include_lib` should only be used when a external library file being included;
* `-spec Function(ArgType1, ..., ArgTypeN) -> ReturnType.` is what I've been used from the beginning, as stated in the [official documentation](http://erlang.org/doc/reference_manual/typespec.html#id79031)

I thought there are no needs to discuss the changes effects any further since these changes are self-explanatory.

I know they both address compile problems in Erlang/OTP 19, but different problems however, at least in separate commits?

**Comment by okeuday** [comment]
@smilerlee Now the changes are in separate commits.

**Comment by smilerlee** [comment]
@okeuday thanks.
@motobob what do you think?

**Comment by motobob** [comment]
thnx for splitting commits. 
I'm okay as it not feasible for me to check if there are any typos. So I will trust travis/dialyzer here that at least current consumers are not broken. 

@okeuday thank you for this great effort of preparation for R19 and making dialyzer more happy.

i'll submit a separate Enhancement here to just not forget to add R19 to the auto builds.

**Pull request merged**
